CREATE TABLE member
(
    member_id   BIGINT       NOT NULL generated by default as identity,
    member_name VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    PRIMARY KEY (member_id)
);

CREATE TABLE RESTAURANT
(
    rest_id      BIGINT       NOT NULL generated by default as identity,
    rest_name    VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255),
    cuisine      VARCHAR(255) NOT NULL,
    rating       DOUBLE       NOT NULL,
    image        VARCHAR(255),
    latitude     DOUBLE,
    longitude    DOUBLE,
    distance     DOUBLE       NOT NULL,
    PRIMARY KEY (rest_id)
);

CREATE TABLE MENU
(
    menu_id   BIGINT       NOT NULL AUTO_INCREMENT,
    menu_name VARCHAR(255) NOT NULL,
    price     INT,
    image     VARCHAR(255),
    rest_id   BIGINT,
    PRIMARY KEY (menu_id),
    FOREIGN KEY (rest_id) REFERENCES restaurant (rest_id)
);

CREATE TABLE Wait
(
    id          BIGINT PRIMARY KEY AUTO_INCREMENT,
    wait_number INT      NOT NULL,
    start_time  DATETIME NOT NULL,
    rest_id     BIGINT   NOT NULL,
    member_id   BIGINT   NOT NULL,
    FOREIGN KEY (rest_id) REFERENCES restaurant (rest_id),
    FOREIGN KEY (member_id) REFERENCES member (member_id)
);