CREATE TABLE member
(
    member_id   BIGINT       NOT NULL generated by default as identity,
    member_name VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    PRIMARY KEY (member_id)
);